# Generated by Django 3.2.8 on 2023-01-31 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cves', models.TextField(default='CVE-00000-00000')),
                ('info', models.TextField(default='To fix you have to ____')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('host_username', models.CharField(max_length=60)),
                ('host_password', models.CharField(max_length=60)),
                ('host_OS', models.PositiveSmallIntegerField(choices=[(1, 'Linux'), (2, 'Windows')])),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(default='Enter report here')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.host')),
            ],
        ),
    ]
