# Generated by Django 3.2.8 on 2023-01-02 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CVE', models.CharField(max_length=60)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.host')),
            ],
        ),
    ]
