# Generated by Django 3.2.8 on 2023-01-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_auto_20230127_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='organization',
        ),
    ]
