# Generated by Django 3.2.8 on 2023-01-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_auto_20230103_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='cve',
            field=models.TextField(default='cve-2000-2000'),
            preserve_default=False,
        ),
    ]
