# Generated by Django 3.2.8 on 2023-01-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_cve_cve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cve',
            old_name='cve',
            new_name='cves',
        ),
    ]
