# Generated by Django 3.2.8 on 2023-01-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_rename_cve_cve_cves'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='hostname',
            field=models.CharField(default='default-host', max_length=100),
            preserve_default=False,
        ),
    ]
