# Generated by Django 3.2.8 on 2023-01-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_host_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='cves',
            field=models.TextField(null=True),
        ),
    ]
