# Generated by Django 3.2.8 on 2023-01-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_alter_cve_cves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
