# Generated by Django 3.2.8 on 2023-01-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_alter_cve_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='cves',
            field=models.TextField(),
        ),
    ]
