# Generated by Django 3.2.8 on 2023-01-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_alter_cve_cves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='cves',
            field=models.TextField(default='CVE-00000-00000'),
        ),
    ]
