# Generated by Django 3.2.8 on 2023-01-04 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_alter_cve_cves'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instructions', models.TextField()),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.cve')),
            ],
        ),
    ]
