# Generated by Django 3.2.8 on 2023-01-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_auto_20230104_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructions',
            old_name='instructions',
            new_name='instruction',
        ),
    ]
