# Generated by Django 3.2.8 on 2023-01-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_rename_instructions_instructions_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructions',
            name='instruction',
            field=models.TextField(default='To fix you have to ____'),
        ),
    ]
