# Generated by Django 3.2.8 on 2023-01-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0014_alter_instructions_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_OS',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Linux'), (2, 'Windows')], default=1),
            preserve_default=False,
        ),
    ]
