# Generated by Django 3.2.8 on 2023-01-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0015_host_host_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cve',
            name='Organization',
        ),
        migrations.RemoveField(
            model_name='cve',
            name='user',
        ),
    ]
