# Generated by Django 3.2.8 on 2023-01-10 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0016_auto_20230107_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(default='Enter report here')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.host')),
            ],
        ),
        migrations.AddField(
            model_name='cve',
            name='info',
            field=models.TextField(default='To fix you have to ____'),
        ),
        migrations.DeleteModel(
            name='Instructions',
        ),
    ]
