image: python:3.10-slim-buster


cache:
  paths:
    - .pip
    - .cache

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

stages:
  - test
  - deploy


test:
  stage: test
  script:
    - python manage.py test

deploy:
  stage: deploy
  script:
    - echo "Ready for deployment..."
  only:
    - main


