image: docker:stable

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t cybrelle-web-web .
    - docker login registry.digitalocean.com -u laineytubbs@cybrelle.io -p dop_v1_147d0f347ac7a4af3bb8e45858682b10f7230d05c4b39776c8dd508d9bc05491
    - docker tag cybrelle-web-web registry.digitalocean.com/cybrelle-registry/cybrelle-web-web
    - docker push registry.digitalocean.com/cybrelle-registry/cybrelle-web-web

deploy:
  stage: deploy
  script:
    - echo "Deployment logic goes here"
