image: python:3.10-slim-buster

cache:
  paths:
    - .pip
    - .cache

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - export DJANGO_SETTINGS_MODULE=Cybrelle.settings
    - pip install dj-database-url
    - python manage.py test

build:
  stage: build
  image: docker:20.10
  services:
    - docker:20.10-dind
  script:
    - docker login -p $DOAPITOKEN registry.digitalocean.com
    - docker build .
    - docker tag cybrelle-web registry.digitalocean.com/cybrelle-registry/cybrelle-web
    - docker push registry.digitalocean.com/cybrelle-registry/cybrelle-web

deploy:
  stage: deploy
  script:
    - echo "Ready for deployment..."
  only:
    - main
