image: docker:20.10

stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY: registry.digitalocean.com/cybrelle-registry
  DOCKER_IMAGE: $DOCKER_REGISTRY/cybrelle-web-web
  DOCKER_BUILD_ARGS: "--pull"
  DOCKER_PUSH_ARGS: ""

before_script:
  - echo $DOCKER_REGISTRY_PASSWORD | docker login $DOCKER_REGISTRY -u laineytubbs@cybrelle.io --password-stdin

build:
  stage: build
  script:
    - docker build $DOCKER_BUILD_ARGS -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_PUSH_ARGS
    - docker push $DOCKER_IMAGE:latest $DOCKER_PUSH_ARGS

deploy:
  stage: deploy
  script:
    - echo "Deploying Cybrelle"
    # Add deployment steps here, e.g. pulling the image on production server
