image: python:3.10-slim-buster


cache:
  paths:
    - .pip
    - .cache

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

stages:
  - build
  - deploy




build:
  stage: build
  image: docker:20.10
  services:
    - docker:20.10-dind
  script:

    - docker login -p $DOAPITOKEN registry.digitalocean.com/cybrelle-registry
    - docker compose build
    - docker tag cybrelle-web registry.digitalocean.com/cybrelle-registry/cybrelle-web
    - docker push registry.digitalocean.com/cybrelle-registry/cybrelle-web

deploy:
  stage: deploy
  script:
    - echo "Ready for deployment..."
  only:
    - main


