image: python:3.10


cache:
  paths:
    - .pip
    - .cache

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

stages:
  - test
  - build_image
  - deploy


test:
  stage: test
  script:
    - python manage.py test
build_image:
  image: docker:20.10
  services:
    - docker:20.10-dind
  variables:
    - DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p REGISTRY_PASS registry.digitalocean.com
  script:
    - docker build -t cybrelle-django registry.digitalocean.com/cybrelle-registry/cybrelle-django
    - docker push registry.digitalocean.com/cybrelle-registry/cybrelle-django
deploy:
  stage: deploy
  script:
    - echo "Ready for deployment..."
  only:
    - main
