FROM python:3.10-slim-buster

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app files
COPY . .

# Collect the static files
RUN python manage.py collectstatic --noinput

# # Run the frontend build
# RUN sh -c "cd frontend && npm install && npm run build"

# # Copy the built frontend files to the django app
# RUN cp -r frontend/build/ static/

# Expose the port that the app will run on
EXPOSE 8000

RUN pip install gunicorn

# Start the app


CMD ["gunicorn", "--workers=4", "--bind=0.0.0.0:8000", "Cybrelle.wsgi.application"]