version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-django
    volumes:
      - static_volume:/frontend
      - media_volume:/media
    command:  python manage.py runserver 0.0.0.0:8000
 

volumes:
  static_volume:
  media_volume:
