version: '3'



services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: cybrelle_web_prod_local_django
    container_name: cybrelle_web_prod_local_django
    
    # volumes:
    #   - .:/app:z
    # env_file:
    #   - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: /start

  
  # docs:
  #   image: cybrelle_web_prod_local_docs
  #   container_name: cybrelle_web_prod_local_docs
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./cybrelle_web_prod:/app/cybrelle_web_prod:z
  #   ports:
  #     - "9000:9000"
  #   command: /start-docs
