# Generated by Django 3.2.8 on 2023-01-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='industry',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
