apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  secretName: acme-issuer
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - cybrelle.io