
apiVersion: v1
kind: Secret
metadata:
  name: godaddy-api-key-secret
  namespace: cert-manager
type: Opaque
stringData:
  # Configure your API Key or Credentials here...
  # ---
  # API Key:
  api-key: fYAyBPYBCzJZ_8HYTBbBZuDFLAKbrjYqp65
  # - or -
  # Token:
  # api-token: your-api-token